import { writeFileSync } from "node:fs";
import {
  ActivityCatalogSchema,
  type Activity,
} from "../src/engine/catalog";

type Draft = Omit<Activity, "id">;

const items: Draft[] = [
  // ---- craft (11) ----
  {
    name: "レザークラフトのキットで小物を作る",
    category: "craft",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "手を動かしているうちに時間を忘れられる、ひとり時間向きのものづくり。",
    first_step: "近くの手芸店か通販で、初心者向けのキーケースキットを1つ選ぶ。",
    link: null,
  },
  {
    name: "消しゴムはんこを彫って年賀状に使う",
    category: "craft",
    indoor: true,
    with: ["solo", "friends"],
    energy: "low",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "彫るほど図案が愛着に変わる、細かい作業が得意な人向けの手仕事。",
    first_step: "彫刻刀セットと消しゴムはんこ用のゴム板を用意する。",
    link: null,
  },
  {
    name: "刺し子でコースターを一枚仕上げる",
    category: "craft",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [60, 150],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "一定のリズムで針を刺すうち、頭の中が静かになっていく手仕事。",
    first_step: "刺し子キットを1つ買って、図案が印刷された布を用意する。",
    link: null,
  },
  {
    name: "プラモデルを1個組み立てる",
    category: "craft",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [90, 240],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "パーツを切り出して組み上げるだけで、一区切りの達成感が得られる。",
    first_step: "気になっているキットを1つ選んで、ニッパーと一緒に用意する。",
    link: null,
  },
  {
    name: "折り紙で立体作品に挑戦する",
    category: "craft",
    indoor: true,
    with: ["solo", "friends", "family"],
    energy: "low",
    minutes: [30, 90],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "紙一枚あればすぐ始められて、家族と一緒でも一人でも楽しめる。",
    first_step: "折り紙用の紙と、作りたい作品の折り方動画を1本探す。",
    link: null,
  },
  {
    name: "手ぬぐいを藍染めして自分だけの一枚を作る",
    category: "craft",
    indoor: true,
    with: ["solo", "partner"],
    energy: "medium",
    minutes: [120, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "染まっていく色の変化を眺めるだけでも楽しい、非日常感のある手仕事。",
    first_step: "藍染めキットを注文し、染める手ぬぐいや布を用意する。",
    link: null,
  },
  {
    name: "木製パズルやミニチュア模型を組み立てる",
    category: "craft",
    indoor: true,
    with: ["solo", "family"],
    energy: "low",
    minutes: [60, 150],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "細かいパーツを揃えて完成させる過程が、静かに集中したい日に合う。",
    first_step: "木製の組み立てキットを1つ選んで手元に用意する。",
    link: null,
  },
  {
    name: "毛糸でマフラーの編み始めに挑戦する",
    category: "craft",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [60, 240],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["autumn", "winter"],
    needs_prep: true,
    pitch: "一目ずつ編み目が増えていく手応えが、じっくり過ごしたい日にちょうどいい。",
    first_step: "初心者向けの棒針セットと毛糸玉を1つ用意する。",
    link: null,
  },
  {
    name: "陶芸体験用の粘土で器を1つ成形する",
    category: "craft",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "medium",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "粘土をこねて形にする作業は、無心になれる時間を作ってくれる。",
    first_step: "陶芸体験ができる教室や工房を1件調べて予約する。",
    link: null,
  },
  {
    name: "フェルトでマスコットを1体作る",
    category: "craft",
    indoor: true,
    with: ["solo", "family"],
    energy: "low",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "小さな作品なら数時間で完成し、できあがりがそのまま部屋に飾れる。",
    first_step: "フェルト手芸のキットを1つ選んで材料をそろえる。",
    link: null,
  },
  {
    name: "アクセサリーをレジンで1点作る",
    category: "craft",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "型に流し込んで硬化を待つだけで、オリジナルの一点ものができる。",
    first_step: "レジン液とパーツ、好きなモチーフを手芸店かネットで揃える。",
    link: null,
  },

  // ---- nature (11) ----
  {
    name: "近所の公園でピクニックをする",
    category: "nature",
    indoor: false,
    with: ["solo", "partner", "friends", "family"],
    energy: "low",
    minutes: [60, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: true,
    pitch: "お弁当を広げるだけで、いつもの公園が特別な時間に変わる。",
    first_step: "おにぎりや飲み物を用意して、レジャーシートを持って出かける。",
    link: null,
  },
  {
    name: "河原や海辺を散歩して景色を眺める",
    category: "nature",
    indoor: false,
    with: ["solo", "partner", "friends", "family"],
    energy: "low",
    minutes: [30, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "水辺を歩くだけで気分が切り替わる、準備いらずの気分転換。",
    first_step: "歩きやすい靴に履き替えて、近くの川か海に向かう。",
    link: null,
  },
  {
    name: "植物園や庭園でゆっくり花を見て歩く",
    category: "nature",
    indoor: false,
    with: ["solo", "partner", "family"],
    energy: "low",
    minutes: [60, 150],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: false,
    pitch: "季節の花を眺めながら歩くだけで、ゆったりした気持ちになれる。",
    first_step: "近くの植物園か庭園を1つ調べて開園時間を確認する。",
    link: null,
  },
  {
    name: "早起きして近所で日の出を見る",
    category: "nature",
    indoor: false,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [30, 60],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "いつもより少し早起きするだけで、特別な一日の始まりになる。",
    first_step: "日の出の時刻を調べて、前夜に見に行く場所を決めておく。",
    link: null,
  },
  {
    name: "バードウォッチングで野鳥を観察する",
    category: "nature",
    indoor: false,
    with: ["solo", "partner"],
    energy: "medium",
    minutes: [90, 180],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "双眼鏡越しに鳥を探すうち、時間を忘れて集中できる。",
    first_step: "双眼鏡を用意し、野鳥が多い公園や河川敷を調べる。",
    link: null,
  },
  {
    name: "星が見える場所で天体観測をする",
    category: "nature",
    indoor: false,
    with: ["partner", "friends", "family"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["autumn", "winter"],
    needs_prep: true,
    pitch: "夜空を見上げるだけで、日常から少し離れた気分になれる。",
    first_step: "その日の天体イベントや星空情報を調べ、暗い場所を探しておく。",
    link: null,
  },
  {
    name: "貸農園や体験農園で野菜の収穫を体験する",
    category: "nature",
    indoor: false,
    with: ["partner", "friends", "family"],
    energy: "medium",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: false,
    pitch: "自分で収穫した野菜は、味も特別に感じられる。",
    first_step: "近隣で収穫体験ができる農園を探して予約する。",
    link: null,
  },
  {
    name: "川や池で釣りをする",
    category: "nature",
    indoor: false,
    with: ["solo", "partner", "friends"],
    energy: "medium",
    minutes: [120, 240],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: true,
    pitch: "竿を垂らして待つ時間そのものが、気持ちを落ち着かせてくれる。",
    first_step: "釣り竿と餌を用意し、近くの釣りができる川や池を調べる。",
    link: null,
  },
  {
    name: "山や丘のハイキングコースを歩く",
    category: "nature",
    indoor: false,
    with: ["partner", "friends"],
    energy: "high",
    minutes: [120, 300],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "autumn"],
    needs_prep: true,
    pitch: "体を動かしながら景色も楽しめる、達成感のあるアウトドア。",
    first_step: "距離の短いハイキングコースを1つ選び、歩きやすい靴を用意する。",
    link: null,
  },
  {
    name: "キャンプ場でデイキャンプを楽しむ",
    category: "nature",
    indoor: false,
    with: ["friends", "family"],
    energy: "medium",
    minutes: [180, 360],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: true,
    pitch: "泊まらなくても、火を囲むだけで非日常感を味わえる。",
    first_step: "日帰り利用ができるキャンプ場を探して予約する。",
    link: null,
  },
  {
    name: "紅葉や桜など季節の景色を見に出かける",
    category: "nature",
    indoor: false,
    with: ["partner", "friends", "family"],
    energy: "low",
    minutes: [60, 180],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "autumn"],
    needs_prep: false,
    pitch: "その時期にしか見られない景色を見るだけで、季節の実感が湧く。",
    first_step: "近隣の見頃スポットを調べて、行きやすい時間を決める。",
    link: null,
  },

  // ---- learning (11) ----
  {
    name: "気になっていた本を1冊読み切る",
    category: "learning",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [60, 240],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "積んでいた本を一気に読み終えると、すっきりした達成感が残る。",
    first_step: "読みかけか気になっていた本を1冊手元に用意する。",
    link: null,
  },
  {
    name: "オンライン講座で新しいスキルの入門編を受ける",
    category: "learning",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "興味はあったけど手を付けていない分野に、短時間で触れられる。",
    first_step: "興味のあるジャンルの入門講座を1つ探して登録する。",
    link: null,
  },
  {
    name: "語学アプリで新しい言語の基礎を進める",
    category: "learning",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [30, 90],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "スキマ時間でも進められて、少しずつ達成感が積み上がる。",
    first_step: "気になる言語の学習アプリを1つインストールする。",
    link: null,
  },
  {
    name: "ドキュメンタリーを見て知らない分野を知る",
    category: "learning",
    indoor: true,
    with: ["solo", "partner", "family"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "知らない世界を映像で覗くだけで、視野が少し広がる。",
    first_step: "配信サービスで気になるテーマのドキュメンタリーを1本選ぶ。",
    link: null,
  },
  {
    name: "博物館や科学館で展示をじっくり見る",
    category: "learning",
    indoor: true,
    with: ["solo", "partner", "friends", "family"],
    energy: "low",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "普段考えない分野の展示を見ると、頭の中がリフレッシュされる。",
    first_step: "近くの博物館や科学館を1つ調べて開館時間を確認する。",
    link: null,
  },
  {
    name: "図書館にこもって気になるテーマを調べる",
    category: "learning",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [90, 180],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "気になっていたことをまとめて調べると、モヤモヤがすっきりする。",
    first_step: "調べたいテーマを1つ決めて、近くの図書館へ向かう。",
    link: null,
  },
  {
    name: "プログラミングの小さな個人プロジェクトを進める",
    category: "learning",
    indoor: true,
    with: ["solo"],
    energy: "medium",
    minutes: [90, 240],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "誰にも急かされず、自分のペースで手を動かして形にできる。",
    first_step: "作りたい小さな機能やツールを1つ決めて、環境を開く。",
    link: null,
  },
  {
    name: "歴史や地元の成り立ちを調べて街歩きしてみる",
    category: "learning",
    indoor: false,
    with: ["solo", "partner"],
    energy: "medium",
    minutes: [90, 180],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "知識を持って歩くと、見慣れた街が違って見えてくる。",
    first_step: "住んでいる街や気になる地域の歴史を軽く検索する。",
    link: null,
  },
  {
    name: "家計簿や資産管理を見直して家計オンライン講座を受ける",
    category: "learning",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "後回しにしがちなお金の整理に、まとまった時間で向き合える。",
    first_step: "家計簿アプリを開くか、家計管理の入門講座を1つ探す。",
    link: null,
  },
  {
    name: "ポッドキャストで専門家の話をまとめて聞く",
    category: "learning",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "作業をしながらでも聞けて、気軽に知識を広げられる。",
    first_step: "興味のあるテーマのポッドキャストを1つ選んで再生する。",
    link: null,
  },
  {
    name: "資格試験の過去問を1年分解いてみる",
    category: "learning",
    indoor: true,
    with: ["solo"],
    energy: "medium",
    minutes: [120, 240],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "まとまった時間だからこそ、腰を据えて実力を確認できる。",
    first_step: "目標にしている資格の過去問題集を1年分用意する。",
    link: null,
  },

  // ---- sports (11) ----
  {
    name: "ジョギングで近所を軽く走る",
    category: "sports",
    indoor: false,
    with: ["solo"],
    energy: "high",
    minutes: [30, 60],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "短時間でも体を動かすと、頭がすっきりして気分が切り替わる。",
    first_step: "動きやすい服とシューズに着替えて、いつもより少し長いコースを走る。",
    link: null,
  },
  {
    name: "サイクリングで少し遠出する",
    category: "sports",
    indoor: false,
    with: ["solo", "partner", "friends"],
    energy: "high",
    minutes: [60, 180],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: true,
    pitch: "電車や車では気づかない景色を、自分のペースで楽しめる。",
    first_step: "自転車を点検し、行き先を1つ決めてルートを調べる。",
    link: null,
  },
  {
    name: "プールで泳ぐ",
    category: "sports",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "high",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "全身を使って泳ぐと、運動不足の解消と気分転換が同時にできる。",
    first_step: "近くの屋内プールの営業時間を調べて水着を用意する。",
    link: null,
  },
  {
    name: "ボルダリングジムで壁を登る",
    category: "sports",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "high",
    minutes: [90, 150],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "登るルートを考えながら全身を使うので、頭も体もすっきりする。",
    first_step: "近くのボルダリングジムの体験プランを調べて予約する。",
    link: null,
  },
  {
    name: "テニスやバドミントンを友人と打ち合う",
    category: "sports",
    indoor: false,
    with: ["friends"],
    energy: "high",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "球を打ち返すだけの単純な動きが、いい気分転換になる。",
    first_step: "ラケットとコートを用意し、友人を1人誘う。",
    link: null,
  },
  {
    name: "ヨガのオンライン動画で体をほぐす",
    category: "sports",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [30, 60],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "マット一枚のスペースがあれば、自宅で静かに体を整えられる。",
    first_step: "ヨガマットを敷いて、動画サイトで初心者向けのレッスンを探す。",
    link: null,
  },
  {
    name: "卓球場で気軽に卓球をする",
    category: "sports",
    indoor: true,
    with: ["partner", "friends", "family"],
    energy: "medium",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "ルールが単純で、久しぶりの相手ともすぐに盛り上がれる。",
    first_step: "近くの卓球場やレンタル施設を調べて予約する。",
    link: null,
  },
  {
    name: "フットサルやバスケを仲間内で楽しむ",
    category: "sports",
    indoor: false,
    with: ["friends"],
    energy: "high",
    minutes: [90, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "仲間と汗を流すと、運動と交流を同時に満たせる。",
    first_step: "フットサルコートを予約し、メンバーに声をかける。",
    link: null,
  },
  {
    name: "ボウリングでスコアを競う",
    category: "sports",
    indoor: true,
    with: ["partner", "friends", "family"],
    energy: "medium",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "力加減を工夫するだけで盛り上がる、幅広い世代で楽しめる遊び。",
    first_step: "近くのボウリング場の空き状況を確認する。",
    link: null,
  },
  {
    name: "近所の坂道や階段を使って軽い筋トレをする",
    category: "sports",
    indoor: false,
    with: ["solo"],
    energy: "high",
    minutes: [20, 40],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "道具がなくても、坂道や階段だけで手軽に体を追い込める。",
    first_step: "近所で使えそうな坂道か階段を1か所見つけておく。",
    link: null,
  },
  {
    name: "ダンスのオンラインレッスンで新しい振付を覚える",
    category: "sports",
    indoor: true,
    with: ["solo", "partner"],
    energy: "medium",
    minutes: [45, 90],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "一曲分の振り付けを覚えるだけで、達成感と運動が両立できる。",
    first_step: "好きな曲のダンスレッスン動画を1本選んで再生する。",
    link: null,
  },

  // ---- food (11) ----
  {
    name: "話題のパン屋やカフェを食べ歩きする",
    category: "food",
    indoor: false,
    with: ["partner", "friends", "family"],
    energy: "low",
    minutes: [60, 150],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "気になっていたお店を巡るだけで、休日らしい満足感が得られる。",
    first_step: "行きたいお店を2〜3軒リストアップしてルートを決める。",
    link: null,
  },
  {
    name: "いつもと違うジャンルの料理を1品作ってみる",
    category: "food",
    indoor: true,
    with: ["solo", "partner", "family"],
    energy: "medium",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "慣れない料理に挑戦する時間そのものが、ちょっとした冒険になる。",
    first_step: "作ったことのないジャンルのレシピを1つ選び、材料を確認する。",
    link: null,
  },
  {
    name: "パン作りに挑戦して焼き立てを食べる",
    category: "food",
    indoor: true,
    with: ["solo", "partner", "family"],
    energy: "medium",
    minutes: [120, 240],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "発酵を待つ時間も含めて、家じゅうがいい匂いになる贅沢な過程。",
    first_step: "失敗しにくいパンのレシピを1つ選び、材料をそろえる。",
    link: null,
  },
  {
    name: "お取り寄せグルメを頼んでゆっくり味わう",
    category: "food",
    indoor: true,
    with: ["solo", "partner", "family"],
    energy: "low",
    minutes: [30, 90],
    budget: "unlimited",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "家から出なくても、特別な一品でちょっとしたご褒美気分になれる。",
    first_step: "話題になっているお取り寄せグルメを1つ選んで注文する。",
    link: null,
  },
  {
    name: "コーヒーや紅茶の淹れ方を研究してカフェタイムを楽しむ",
    category: "food",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [30, 60],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "淹れ方を少し変えるだけで、いつもの一杯が特別な時間になる。",
    first_step: "豆や茶葉を用意し、いつもと違う淹れ方を1つ試す。",
    link: null,
  },
  {
    name: "商店街の食べ歩きで知らないお店を開拓する",
    category: "food",
    indoor: false,
    with: ["partner", "friends"],
    energy: "low",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "昔ながらの商店街を歩くと、知らなかった名店に出会える。",
    first_step: "近くの商店街を1つ選び、気になるお店を2軒ピックアップする。",
    link: null,
  },
  {
    name: "家で本格的なブランチを作ってゆっくり食べる",
    category: "food",
    indoor: true,
    with: ["solo", "partner", "family"],
    energy: "low",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "時間を気にせず品数を増やすだけで、休日らしいごちそう気分になる。",
    first_step: "作りたいブランチメニューを2〜3品決めて買い出しをする。",
    link: null,
  },
  {
    name: "スパイスから作るカレーに挑戦する",
    category: "food",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "medium",
    minutes: [90, 150],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "スパイスを調合する過程そのものが、実験のような楽しさがある。",
    first_step: "基本のスパイス数種と作り方のレシピを用意する。",
    link: null,
  },
  {
    name: "友人を呼んでホームパーティー用の持ち寄り料理を作る",
    category: "food",
    indoor: true,
    with: ["friends"],
    energy: "medium",
    minutes: [120, 240],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "それぞれ一品ずつ持ち寄るだけで、準備の負担を抑えつつ盛り上がれる。",
    first_step: "友人に声をかけて日程を決め、担当する料理を1品考える。",
    link: null,
  },
  {
    name: "地元の朝市や産直市場で食材を選んで料理する",
    category: "food",
    indoor: false,
    with: ["partner", "family"],
    energy: "medium",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "選んだ食材で何を作るか考える過程も含めて楽しめる。",
    first_step: "近くで開催されている朝市や産直市場を調べる。",
    link: null,
  },
  {
    name: "スイーツ作りでお菓子を焼く",
    category: "food",
    indoor: true,
    with: ["solo", "family"],
    energy: "medium",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "焼き上がりを待つ時間も含めて、甘い香りに包まれる時間になる。",
    first_step: "作りたいお菓子のレシピを1つ選んで材料をそろえる。",
    link: null,
  },

  // ---- appreciation (11) ----
  {
    name: "気になっていた映画を映画館で観る",
    category: "appreciation",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "low",
    minutes: [120, 150],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "大きなスクリーンに集中するだけで、日常から離れられる。",
    first_step: "上映中の映画を1本選んで上映時間を確認する。",
    link: null,
  },
  {
    name: "配信サービスで映画を1本じっくり観る",
    category: "appreciation",
    indoor: true,
    with: ["solo", "partner", "family"],
    energy: "low",
    minutes: [90, 150],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "外出しなくても、集中して1本観きるだけで満足感が得られる。",
    first_step: "気になっていた映画を配信サービスで1本選ぶ。",
    link: null,
  },
  {
    name: "美術館で企画展をじっくり見て回る",
    category: "appreciation",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "low",
    minutes: [90, 150],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "作品の前で立ち止まる時間そのものが、贅沢な気分転換になる。",
    first_step: "開催中の企画展を1つ調べてチケットを確認する。",
    link: null,
  },
  {
    name: "ライブハウスやコンサートで生演奏を聴く",
    category: "appreciation",
    indoor: true,
    with: ["partner", "friends"],
    energy: "medium",
    minutes: [120, 180],
    budget: "unlimited",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "生の音を浴びる体験は、配信では味わえない高揚感がある。",
    first_step: "気になるアーティストのライブ日程を調べてチケットを確認する。",
    link: null,
  },
  {
    name: "好きなアーティストのアルバムを通しで聴き込む",
    category: "appreciation",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [40, 80],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "1枚を通して聴くと、シングル曲だけでは気づかない魅力が見えてくる。",
    first_step: "聴きたいアルバムを1枚選び、通しで再生する時間を確保する。",
    link: null,
  },
  {
    name: "舞台やお笑いライブを観に行く",
    category: "appreciation",
    indoor: true,
    with: ["partner", "friends"],
    energy: "medium",
    minutes: [90, 150],
    budget: "unlimited",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "その場の空気を共有する体験が、笑いや感動を何倍にもしてくれる。",
    first_step: "行けそうな公演を1つ探し、チケットの有無を確認する。",
    link: null,
  },
  {
    name: "プラネタリウムで星空の解説を見る",
    category: "appreciation",
    indoor: true,
    with: ["partner", "family"],
    energy: "low",
    minutes: [45, 60],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "座っているだけで満点の星空が楽しめる、天候に左右されない鑑賞。",
    first_step: "近くのプラネタリウムの上映スケジュールを調べる。",
    link: null,
  },
  {
    name: "写真展やギャラリーを気ままに巡る",
    category: "appreciation",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "決まったルートがなくても、気になった作品の前で自由に立ち止まれる。",
    first_step: "近くで開催中の写真展やギャラリーを1つ調べる。",
    link: null,
  },
  {
    name: "話題のアニメやドラマを一気見する",
    category: "appreciation",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [120, 240],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "続きが気になる作品を一気に観ると、没頭できる満足感がある。",
    first_step: "観たかった作品を1つ選んで最初のエピソードを再生する。",
    link: null,
  },
  {
    name: "落語や寄席で古典芸能に触れる",
    category: "appreciation",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [90, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "一つの話芸にじっくり耳を傾けるだけで、新鮮な気分転換になる。",
    first_step: "近くの寄席や落語会のスケジュールを調べる。",
    link: null,
  },
  {
    name: "水族館で生き物をのんびり眺める",
    category: "appreciation",
    indoor: true,
    with: ["partner", "family", "friends"],
    energy: "low",
    minutes: [90, 150],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "水槽の前でぼーっと眺めているだけで、気持ちが落ち着いてくる。",
    first_step: "近くの水族館の営業時間を調べる。",
    link: null,
  },

  // ---- rest (12) ----
  {
    name: "何も予定を入れずに家でゴロゴロして過ごす",
    category: "rest",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [60, 480],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "何もしないと決めることも、立派な休日の過ごし方のひとつ。",
    first_step: "スマホの通知をオフにして、ソファや布団に体を預ける。",
    link: null,
  },
  {
    name: "昼寝をしてたまった疲れをリセットする",
    category: "rest",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [30, 90],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "短い昼寝でも、頭と体の疲れをしっかりリセットできる。",
    first_step: "カーテンを閉めて、アラームを20〜30分後にセットする。",
    link: null,
  },
  {
    name: "スマホを置いて静かにお茶を飲む時間を作る",
    category: "rest",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [20, 40],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "スマホから離れるだけで、頭の中の情報量がぐっと減って落ち着く。",
    first_step: "お気に入りのお茶を淹れて、スマホを別の部屋に置く。",
    link: null,
  },
  {
    name: "湯船にゆっくり浸かって半身浴をする",
    category: "rest",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [20, 40],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "お湯に浸かる時間そのものが、心身をゆるめてくれる。",
    first_step: "湯船にお湯を張り、読みたい本か聴きたい音楽を用意する。",
    link: null,
  },
  {
    name: "好きな音楽をかけながら部屋の片づけをゆるくする",
    category: "rest",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [30, 90],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "音楽に合わせて体を動かすだけで、片づけも気分転換になる。",
    first_step: "好きなプレイリストを流して、片づける場所を1か所だけ決める。",
    link: null,
  },
  {
    name: "アロマを焚いてソファで読みかけの本を眺める",
    category: "rest",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [30, 60],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "香りと読書を組み合わせるだけで、いつもの部屋が休息の空間になる。",
    first_step: "アロマディフューザーをセットし、読みかけの本をソファに持っていく。",
    link: null,
  },
  {
    name: "瞑想アプリを使って静かに呼吸を整える",
    category: "rest",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [10, 30],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "数分呼吸に集中するだけで、忙しかった頭がすっと静かになる。",
    first_step: "瞑想アプリを開いて、初心者向けの短いセッションを選ぶ。",
    link: null,
  },
  {
    name: "マッサージチェアや指圧グッズで体をほぐす",
    category: "rest",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [20, 40],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "座っているだけで、こり固まった体をゆるめてもらえる。",
    first_step: "マッサージチェアのあるお店を調べるか、家の指圧グッズを用意する。",
    link: null,
  },
  {
    name: "朝ゆっくり起きてベッドの中で動画や漫画を楽しむ",
    category: "rest",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [30, 90],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "起きる時間を決めないだけで、朝から特別なのんびり感が味わえる。",
    first_step: "アラームを切って、ベッドの中で見たいものを1つ用意しておく。",
    link: null,
  },
  {
    name: "好きな香りの入浴剤でお風呂タイムを贅沢にする",
    category: "rest",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [20, 40],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "入浴剤を1つ変えるだけで、いつものお風呂が特別な時間になる。",
    first_step: "評判の入浴剤を1つ買って、お湯を張る。",
    link: null,
  },
  {
    name: "ハンモックやリクライニングチェアで外の風を感じながらうたた寝する",
    category: "rest",
    indoor: false,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [30, 60],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: false,
    pitch: "外の空気を感じながらうとうとする時間は、室内とは違う心地よさがある。",
    first_step: "ベランダや庭にハンモックかリクライニングチェアを用意する。",
    link: null,
  },
  {
    name: "一日中パジャマのまま家で過ごすと決めてのんびりする",
    category: "rest",
    indoor: true,
    with: ["solo", "partner", "family"],
    energy: "low",
    minutes: [120, 480],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "着替えないと決めるだけで、体も頭もしっかり休むモードに入れる。",
    first_step: "予定をすべて空けて、パジャマのまま過ごすと決める。",
    link: null,
  },

  // ---- social (11) ----
  {
    name: "友人を家に呼んでゲーム会をする",
    category: "social",
    indoor: true,
    with: ["friends"],
    energy: "medium",
    minutes: [120, 240],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "好きなゲームを囲むだけで、自然と会話も盛り上がる。",
    first_step: "友人に声をかけて日程を決め、遊ぶゲームを1つ用意する。",
    link: null,
  },
  {
    name: "オンライン通話で遠方の友人とゆっくり話す",
    category: "social",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [30, 90],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "会いに行けなくても、顔を見て話すだけで気持ちがつながる。",
    first_step: "話したい友人に連絡して、通話できる時間を約束する。",
    link: null,
  },
  {
    name: "地域のボランティア活動に参加する",
    category: "social",
    indoor: false,
    with: ["solo", "friends"],
    energy: "medium",
    minutes: [120, 240],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "誰かの役に立つ実感が、いつもと違う満足感を連れてきてくれる。",
    first_step: "近くで参加できるボランティア募集を1つ調べる。",
    link: null,
  },
  {
    name: "昔からの友人と喫茶店で近況を話す",
    category: "social",
    indoor: true,
    with: ["friends"],
    energy: "low",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "顔を合わせて話すだけで、離れていた時間がすぐ縮まる。",
    first_step: "会いたい友人を1人思い浮かべて連絡してみる。",
    link: null,
  },
  {
    name: "家族と一緒に近所を散歩しながらおしゃべりする",
    category: "social",
    indoor: false,
    with: ["family"],
    energy: "low",
    minutes: [30, 90],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "歩きながらの会話は、向き合って話すより気楽に言葉が出てくる。",
    first_step: "家族を誘って、散歩に出るタイミングを決める。",
    link: null,
  },
  {
    name: "パートナーと一緒に料理をしながら一日の話をする",
    category: "social",
    indoor: true,
    with: ["partner"],
    energy: "medium",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "手を動かしながらの会話は、自然体で話しやすい。",
    first_step: "一緒に作る料理を1品決めて、材料を用意する。",
    link: null,
  },
  {
    name: "習い事の体験レッスンに友人を誘って参加する",
    category: "social",
    indoor: true,
    with: ["friends"],
    energy: "medium",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "一人だと迷う体験レッスンも、友人と一緒なら踏み出しやすい。",
    first_step: "気になる体験レッスンを1つ探し、友人を誘ってみる。",
    link: null,
  },
  {
    name: "地域のマルシェやフリーマーケットを友人とまわる",
    category: "social",
    indoor: false,
    with: ["friends", "family"],
    energy: "low",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "掘り出し物を探しながら歩くだけで、自然と会話が弾む。",
    first_step: "今週末に近くで開催されるマルシェかフリマを探す。",
    link: null,
  },
  {
    name: "親戚や実家に顔を出してゆっくり過ごす",
    category: "social",
    indoor: true,
    with: ["family"],
    energy: "low",
    minutes: [120, 300],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "たまに顔を出すだけで、家族との時間の積み重ねになる。",
    first_step: "実家や親戚に連絡して、訪ねる日程を決める。",
    link: null,
  },
  {
    name: "子どもと一緒に公園で遊具遊びをする",
    category: "social",
    indoor: false,
    with: ["family"],
    energy: "medium",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "一緒に体を動かして遊ぶだけで、子どもとの距離がぐっと縮まる。",
    first_step: "近くの公園を1つ選んで、動きやすい服で出かける。",
    link: null,
  },
  {
    name: "オンラインコミュニティのオフ会に参加してみる",
    category: "social",
    indoor: true,
    with: ["friends"],
    energy: "medium",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "普段ネット越しの人と直接会うと、新しいつながりが生まれる。",
    first_step: "参加しているコミュニティのオフ会情報を調べて申し込む。",
    link: null,
  },

  // ---- play (11) ----
  {
    name: "ボードゲームカフェで新作ゲームを遊ぶ",
    category: "play",
    indoor: true,
    with: ["partner", "friends"],
    energy: "medium",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "スタッフに説明してもらいながら、知らないゲームにも気軽に挑戦できる。",
    first_step: "近くのボードゲームカフェを調べて予約する。",
    link: null,
  },
  {
    name: "脱出ゲームに挑戦する",
    category: "play",
    indoor: true,
    with: ["partner", "friends"],
    energy: "medium",
    minutes: [60, 90],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "制限時間の中で謎を解く緊張感が、いい気分転換になる。",
    first_step: "近くの脱出ゲーム施設を調べて予約する。",
    link: null,
  },
  {
    name: "ゲームセンターでクレーンゲームや音楽ゲームを楽しむ",
    category: "play",
    indoor: true,
    with: ["partner", "friends", "family"],
    energy: "medium",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "短時間のゲームを何度も楽しめて、気軽に盛り上がれる。",
    first_step: "近くのゲームセンターに出かけて、遊びたい機種を探す。",
    link: null,
  },
  {
    name: "家で対戦できるテレビゲームをやり込む",
    category: "play",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "medium",
    minutes: [60, 240],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "好きなだけ時間を使えるので、思い切り遊びに没頭できる。",
    first_step: "遊びたいゲームソフトを1本選んで起動する。",
    link: null,
  },
  {
    name: "カラオケで好きな曲を歌いまくる",
    category: "play",
    indoor: true,
    with: ["partner", "friends"],
    energy: "high",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "声を出して歌うだけで、たまったストレスがすっきり発散できる。",
    first_step: "近くのカラオケ店の時間を確認して予約する。",
    link: null,
  },
  {
    name: "謎解きイベントやクイズアプリに挑戦する",
    category: "play",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "medium",
    minutes: [45, 90],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "頭をひねって謎を解く過程が、ちょっとした冒険気分にしてくれる。",
    first_step: "謎解きキットかクイズアプリを1つ用意する。",
    link: null,
  },
  {
    name: "カードゲームやTRPGのルールを覚えてじっくり遊ぶ",
    category: "play",
    indoor: true,
    with: ["friends"],
    energy: "medium",
    minutes: [120, 240],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "ルールを覚えるところから含めて、じっくり没頭できる遊び。",
    first_step: "遊んでみたいカードゲームかTRPGのルールブックを1つ用意する。",
    link: null,
  },
  {
    name: "遊園地やアミューズメントパークで一日遊ぶ",
    category: "play",
    indoor: false,
    with: ["partner", "friends", "family"],
    energy: "high",
    minutes: [240, 480],
    budget: "unlimited",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "朝から夕方まで思い切り遊ぶと、非日常感をたっぷり味わえる。",
    first_step: "行きたい遊園地を1つ決めてチケットや営業時間を確認する。",
    link: null,
  },
  {
    name: "手品やパズルの動画を見て実際にやってみる",
    category: "play",
    indoor: true,
    with: ["solo", "family"],
    energy: "low",
    minutes: [30, 60],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "見て終わりにせず実際に手を動かすと、小さな達成感が得られる。",
    first_step: "手品かパズルの解説動画を1本選んで、必要な道具を用意する。",
    link: null,
  },
  {
    name: "公園でフリスビーやバドミントンを気軽に楽しむ",
    category: "play",
    indoor: false,
    with: ["friends", "family"],
    energy: "medium",
    minutes: [45, 90],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "道具さえあれば、思い立ったらすぐ体を動かして遊べる。",
    first_step: "フリスビーかバドミントンセットを持って、近くの公園に向かう。",
    link: null,
  },
  {
    name: "ペットと一緒に新しい散歩コースを開拓して遊ぶ",
    category: "play",
    indoor: false,
    with: ["solo", "partner", "family"],
    energy: "medium",
    minutes: [30, 90],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "いつもと違う道を歩くだけで、ペットも自分も新鮮な気分になれる。",
    first_step: "まだ歩いたことのない近所のコースを1つ調べる。",
    link: null,
  },

  // ==== 週末6追加分(101-200) ====

  // ---- craft (11) ----
  {
    name: "ガラス細工体験でオリジナルのグラスを作る",
    category: "craft",
    indoor: true,
    with: ["solo", "partner"],
    energy: "medium",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "炎を使う作業に少し緊張しながら向き合う時間が、いい気分転換になる。",
    first_step: "ガラス細工体験ができる工房を探して予約する。",
    link: null,
  },
  {
    name: "アロマキャンドルを手作りする",
    category: "craft",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "low",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "好きな香りを選んで固めていく時間は、贈り物を用意するような楽しさがある。",
    first_step: "キャンドル用ワックスと好きな香りのオイルをセットで揃える。",
    link: null,
  },
  {
    name: "マクラメ編みで壁掛けタペストリーを作る",
    category: "craft",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "紐を結んでいくだけで模様が育っていく、単純作業なのに没頭できる手仕事。",
    first_step: "マクラメ編みの初級キットと壁掛け用のリングを用意する。",
    link: null,
  },
  {
    name: "木工体験でスプーン1本を削り出す",
    category: "craft",
    indoor: true,
    with: ["solo", "partner"],
    energy: "medium",
    minutes: [120, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "木を削るうちに形が生まれていく過程は、地味だけど確かな達成感がある。",
    first_step: "木工体験ができる工房を探し、使う木材の種類を決めておく。",
    link: null,
  },
  {
    name: "刺繍でオリジナルのポーチを仕上げる",
    category: "craft",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "一針ずつ図案が形になっていく様子は、地道だけど飽きずに続けられる。",
    first_step: "刺繍糸と無地のポーチ、簡単な図案を1つ用意する。",
    link: null,
  },
  {
    name: "金継ぎ体験で欠けた器を修復する",
    category: "craft",
    indoor: true,
    with: ["solo", "partner"],
    energy: "medium",
    minutes: [120, 180],
    budget: "unlimited",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "壊れたものを直して使い続けるという発想に触れると、ものの見方が少し変わる。",
    first_step: "金継ぎ体験ができる教室を探し、直したい器があれば持っていく。",
    link: null,
  },
  {
    name: "ステンドグラス風のサンキャッチャーを作る",
    category: "craft",
    indoor: true,
    with: ["solo", "friends"],
    energy: "low",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "光にかざすと表情が変わる小さな作品は、作るのも飾るのも楽しい。",
    first_step: "サンキャッチャー用のガラスパーツとテグスを手芸店かネットで揃える。",
    link: null,
  },
  {
    name: "七宝焼き体験でアクセサリーを作る",
    category: "craft",
    indoor: true,
    with: ["solo", "partner"],
    energy: "medium",
    minutes: [90, 150],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "焼き上がるまで色の変化が予測できないところに、ちょっとした賭け事のような面白さがある。",
    first_step: "七宝焼き体験ができる教室を探して予約する。",
    link: null,
  },
  {
    name: "しめ縄やリースをハンドメイドする",
    category: "craft",
    indoor: true,
    with: ["solo", "partner", "family"],
    energy: "low",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["autumn", "winter"],
    needs_prep: true,
    pitch: "季節の飾りを自分の手で作ると、いつもの年末年始が少し特別になる。",
    first_step: "リース台と好きな木の実や造花の材料を用意する。",
    link: null,
  },
  {
    name: "革の名刺入れをハンドステッチで仕立てる",
    category: "craft",
    indoor: true,
    with: ["solo"],
    energy: "medium",
    minutes: [120, 240],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "革を縫い進めるうちに、道具を使う手つきが少しずつ様になっていく。",
    first_step: "革のキットと縫い針、蝋引き糸をセットで用意する。",
    link: null,
  },
  {
    name: "ミニチュアドールハウスの部屋を組み立てる",
    category: "craft",
    indoor: true,
    with: ["solo", "family"],
    energy: "low",
    minutes: [120, 240],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "小さな部屋を作り込んでいく作業は、時間を忘れて没頭できる。",
    first_step: "作りたい雰囲気のミニチュアドールハウスキットを1つ選ぶ。",
    link: null,
  },

  // ---- nature (11) ----
  {
    name: "パラグライダー体験で空から景色を楽しむ",
    category: "nature",
    indoor: false,
    with: ["solo", "partner", "friends"],
    energy: "high",
    minutes: [120, 240],
    budget: "unlimited",
    weather_ok: ["sunny"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: true,
    pitch: "空を飛ぶという非日常の体験は、一度やると記憶に残り続ける。",
    first_step: "パラグライダー体験ができるスクールを探して予約する。",
    link: null,
  },
  {
    name: "カヤックやSUPで川や湖を漕ぐ",
    category: "nature",
    indoor: false,
    with: ["solo", "partner", "friends"],
    energy: "high",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: true,
    pitch: "水面に近い視点で景色を見るだけで、いつもと違う気分転換になる。",
    first_step: "カヤックかSUPのレンタル・体験ができる場所を探す。",
    link: null,
  },
  {
    name: "渓谷や滝を目指してトレッキングする",
    category: "nature",
    indoor: false,
    with: ["solo", "partner", "friends"],
    energy: "high",
    minutes: [180, 300],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "autumn"],
    needs_prep: true,
    pitch: "歩いた先にしか見られない景色があると思うと、足取りが自然と軽くなる。",
    first_step: "行きたい渓谷や滝のルートと所要時間を調べる。",
    link: null,
  },
  {
    name: "牧場で動物とふれあう",
    category: "nature",
    indoor: false,
    with: ["partner", "family"],
    energy: "medium",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: false,
    pitch: "動物のペースに合わせて過ごす時間は、自然と心がゆるむ。",
    first_step: "近隣でふれあい体験ができる牧場を調べる。",
    link: null,
  },
  {
    name: "静かな森林浴コースをゆっくり歩く",
    category: "nature",
    indoor: false,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: false,
    pitch: "木々に囲まれてただ歩くだけで、頭の中がすっと静かになる。",
    first_step: "近隣で森林浴ができる散策路を1つ調べる。",
    link: null,
  },
  {
    name: "海辺で貝殻や漂着物を拾いながら散歩する",
    category: "nature",
    indoor: false,
    with: ["solo", "partner", "family"],
    energy: "low",
    minutes: [45, 90],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "足元を見ながら歩くだけで、いつもと違う時間の流れ方になる。",
    first_step: "近くの海辺の干潮時刻を調べて出かける。",
    link: null,
  },
  {
    name: "高原でトレイルランニングに挑戦する",
    category: "nature",
    indoor: false,
    with: ["solo", "friends"],
    energy: "high",
    minutes: [90, 180],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: true,
    pitch: "舗装されていない道を走ると、いつものランニングとは違う達成感がある。",
    first_step: "トレイルランができる近隣のコースを調べ、トレイルシューズを用意する。",
    link: null,
  },
  {
    name: "展望台やロープウェイから季節の景色を一望する",
    category: "nature",
    indoor: false,
    with: ["solo", "partner", "friends", "family"],
    energy: "low",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "高い場所から街や自然を見下ろすだけで、気分がすっと切り替わる。",
    first_step: "近隣の展望台やロープウェイの営業時間を調べる。",
    link: null,
  },
  {
    name: "家庭菜園やガーデニングで苗を植える",
    category: "nature",
    indoor: false,
    with: ["solo", "partner", "family"],
    energy: "medium",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "autumn"],
    needs_prep: true,
    pitch: "土に触れて何かを育て始めると、その後の楽しみも長く続く。",
    first_step: "育てたい苗と土、プランターをホームセンターで揃える。",
    link: null,
  },
  {
    name: "川辺でバーベキューを楽しむ",
    category: "nature",
    indoor: false,
    with: ["friends", "family"],
    energy: "medium",
    minutes: [180, 300],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: true,
    pitch: "屋外で火を囲んで食べるだけで、特別な一日になる。",
    first_step: "バーベキューができる河川敷や施設を調べ、食材を買い出しする。",
    link: null,
  },
  {
    name: "夜の砂浜でナイトピクニックをする",
    category: "nature",
    indoor: false,
    with: ["solo", "partner", "friends"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: true,
    pitch: "波音を聞きながら過ごす夜は、昼間とはまったく違う特別感がある。",
    first_step: "防寒具とレジャーシート、飲み物を持って夕方以降に出かける。",
    link: null,
  },

  // ---- learning (11) ----
  {
    name: "投資・資産運用の基礎をオンラインで学ぶ",
    category: "learning",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "難しそうで後回しにしていた話ほど、まとまった時間で一気に理解が進む。",
    first_step: "資産運用の入門講座か解説動画を1つ選んで視聴する。",
    link: null,
  },
  {
    name: "写真の構図や撮り方をオンラインで学び実践する",
    category: "learning",
    indoor: false,
    with: ["solo"],
    energy: "medium",
    minutes: [90, 150],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "少しコツを知るだけで、いつもの散歩道がカメラを向けたくなる景色に変わる。",
    first_step: "構図の基本を解説した動画を1本見てから、近所で試し撮りする。",
    link: null,
  },
  {
    name: "宇宙や天体についての解説動画をまとめて見る",
    category: "learning",
    indoor: true,
    with: ["solo", "family"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "スケールの大きな話に触れると、日々の悩みが少し小さく感じられる。",
    first_step: "宇宙や天体をテーマにした解説動画やドキュメンタリーを1本選ぶ。",
    link: null,
  },
  {
    name: "コーヒーやワインのテイスティングを独学で試す",
    category: "learning",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [60, 90],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "香りや味の違いを言葉にしようとするだけで、いつもの一杯の解像度が上がる。",
    first_step: "飲み比べたい種類を2〜3種類選んで用意する。",
    link: null,
  },
  {
    name: "大学の公開講座(無料オンライン講義)を1つ受ける",
    category: "learning",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "専門家の話を体系立てて聞けると、断片的だった知識がつながっていく。",
    first_step: "興味のある分野の公開講座やオンライン講義を1つ探す。",
    link: null,
  },
  {
    name: "語学交換アプリで海外の人とやり取りする",
    category: "learning",
    indoor: true,
    with: ["solo"],
    energy: "medium",
    minutes: [30, 60],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "実際に誰かとやり取りすると、勉強していた言葉が急に生きた言葉に変わる。",
    first_step: "語学交換アプリをインストールしてプロフィールを整える。",
    link: null,
  },
  {
    name: "タイピング速度向上トレーニングに挑戦する",
    category: "learning",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [20, 40],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "数字で伸びが見える練習は、地味だけど達成感がわかりやすい。",
    first_step: "タイピング練習サイトで現在の速度を測ってみる。",
    link: null,
  },
  {
    name: "将棋や囲碁のルールを覚えて棋譜を並べる",
    category: "learning",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "ルールを覚えるところから含めて、じわじわとのめり込める世界。",
    first_step: "入門書か解説動画でルールをひと通り確認する。",
    link: null,
  },
  {
    name: "地図アプリで知らない土地をバーチャル探検する",
    category: "learning",
    indoor: true,
    with: ["solo", "family"],
    energy: "low",
    minutes: [30, 60],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "行ったことのない街を地図上で歩き回るだけで、ちょっとした旅気分になる。",
    first_step: "気になっている地名を1つ思い浮かべて地図アプリを開く。",
    link: null,
  },
  {
    name: "統計学やデータ分析の基礎をオンラインで学ぶ",
    category: "learning",
    indoor: true,
    with: ["solo"],
    energy: "medium",
    minutes: [90, 150],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "数字の見方が少し変わるだけで、ニュースの読み方まで変わってくる。",
    first_step: "統計の入門講座か解説記事を1つ選んで手を動かしながら読む。",
    link: null,
  },
  {
    name: "手話や点字など初歩のコミュニケーション手段を学ぶ",
    category: "learning",
    indoor: true,
    with: ["solo", "family"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "普段使わない伝え方を知ると、世界の見え方が少し広がる。",
    first_step: "手話か点字の入門動画や解説サイトを1つ見つける。",
    link: null,
  },

  // ---- sports (12) ----
  {
    name: "サーフィン体験に挑戦する",
    category: "sports",
    indoor: false,
    with: ["solo", "friends"],
    energy: "high",
    minutes: [120, 180],
    budget: "unlimited",
    weather_ok: ["sunny"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: true,
    pitch: "波に乗れた瞬間の高揚感は、他では味わえない特別なもの。",
    first_step: "サーフィン体験ができるスクールを探して予約する。",
    link: null,
  },
  {
    name: "スケートボードの練習をする",
    category: "sports",
    indoor: false,
    with: ["solo", "friends"],
    energy: "high",
    minutes: [45, 90],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "少しずつ技ができるようになる過程が、飽きずに続けられる理由になる。",
    first_step: "スケートボードとプロテクターを用意し、近くの練習場所を探す。",
    link: null,
  },
  {
    name: "キックボクシングの体験レッスンを受ける",
    category: "sports",
    indoor: true,
    with: ["solo"],
    energy: "high",
    minutes: [60, 90],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "思い切り体を動かして汗をかくと、たまったモヤモヤが一気に発散できる。",
    first_step: "近くのキックボクシングジムの体験レッスンを予約する。",
    link: null,
  },
  {
    name: "乗馬体験をする",
    category: "sports",
    indoor: false,
    with: ["solo", "partner", "family"],
    energy: "medium",
    minutes: [60, 120],
    budget: "unlimited",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: true,
    pitch: "大きな生き物と息を合わせる感覚は、他のスポーツにはない緊張感と楽しさがある。",
    first_step: "乗馬体験ができる牧場やクラブを探して予約する。",
    link: null,
  },
  {
    name: "屋内スカイダイビング(ウィンドトンネル)体験をする",
    category: "sports",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "high",
    minutes: [60, 90],
    budget: "unlimited",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "空を飛ぶ感覚を安全な屋内で味わえる、なかなかない非日常体験。",
    first_step: "屋内スカイダイビング施設を探して予約する。",
    link: null,
  },
  {
    name: "アイススケートを楽しむ",
    category: "sports",
    indoor: true,
    with: ["partner", "friends", "family"],
    energy: "high",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["autumn", "winter"],
    needs_prep: false,
    pitch: "転びそうになりながら滑る時間は、童心に返れる貴重な機会。",
    first_step: "近くのアイススケート場の営業時間を調べる。",
    link: null,
  },
  {
    name: "トランポリンパークで跳び回る",
    category: "sports",
    indoor: true,
    with: ["partner", "friends", "family"],
    energy: "high",
    minutes: [45, 90],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "ただ跳ぶだけなのに、気づけば全身運動になっている。",
    first_step: "近くのトランポリンパークの予約状況を確認する。",
    link: null,
  },
  {
    name: "日帰り登山でピークを目指す",
    category: "sports",
    indoor: false,
    with: ["solo", "friends"],
    energy: "high",
    minutes: [240, 480],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "autumn"],
    needs_prep: true,
    pitch: "頂上から見える景色は、そこまで歩いた分だけ特別に感じられる。",
    first_step: "日帰りできる山を1つ選び、コースタイムと持ち物を確認する。",
    link: null,
  },
  {
    name: "バッティングセンターで汗を流す",
    category: "sports",
    indoor: true,
    with: ["solo", "friends"],
    energy: "high",
    minutes: [30, 60],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "ボールを打ち返す単純な動きが、意外なほどストレス発散になる。",
    first_step: "近くのバッティングセンターの営業時間を確認する。",
    link: null,
  },
  {
    name: "アーチェリー体験でシューティングを楽しむ",
    category: "sports",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "medium",
    minutes: [60, 90],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "的を狙って集中する時間は、他のことを考える余裕がなくなるほど没頭できる。",
    first_step: "アーチェリー体験ができる施設を探して予約する。",
    link: null,
  },
  {
    name: "ゴルフの打ちっぱなしでスイング練習をする",
    category: "sports",
    indoor: false,
    with: ["solo", "partner", "friends"],
    energy: "medium",
    minutes: [45, 90],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "ボールを打つ音とフォームの確認に集中すると、他の考え事が消えていく。",
    first_step: "近くの打ちっぱなし練習場の料金と営業時間を確認する。",
    link: null,
  },
  {
    name: "フットバッグやスラックラインで公園遊びをする",
    category: "sports",
    indoor: false,
    with: ["solo", "friends"],
    energy: "high",
    minutes: [30, 60],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "道具さえあれば、公園でふらっと始められる気軽な運動遊び。",
    first_step: "スラックラインかフットバッグを持って、広めの公園に向かう。",
    link: null,
  },

  // ---- food (11) ----
  {
    name: "高級レストランでコース料理を楽しむ",
    category: "food",
    indoor: true,
    with: ["partner", "friends"],
    energy: "low",
    minutes: [90, 150],
    budget: "unlimited",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "一皿ごとに驚きがあるコース料理は、特別な日を演出してくれる。",
    first_step: "行ってみたいレストランを1つ選び、予約を取る。",
    link: null,
  },
  {
    name: "お寿司を握る体験をする",
    category: "food",
    indoor: true,
    with: ["solo", "partner", "friends", "family"],
    energy: "medium",
    minutes: [60, 90],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "自分で握った寿司は、味だけでなく達成感もごちそうになる。",
    first_step: "寿司握り体験ができる教室やイベントを探す。",
    link: null,
  },
  {
    name: "チーズや生ハムの食べ比べをする",
    category: "food",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "low",
    minutes: [45, 90],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "少しずつ味の違いを比べる時間は、お酒がなくても十分楽しめる。",
    first_step: "気になる種類のチーズや生ハムを2〜3種類買ってくる。",
    link: null,
  },
  {
    name: "燻製作りに挑戦する",
    category: "food",
    indoor: false,
    with: ["solo", "partner", "friends"],
    energy: "medium",
    minutes: [120, 240],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "煙に包まれるのを待つ時間も含めて、丸ごと楽しめる調理体験。",
    first_step: "燻製器かダンボールで作る簡易キットと食材を用意する。",
    link: null,
  },
  {
    name: "自家製パスタ(生麺)を作る",
    category: "food",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "medium",
    minutes: [90, 150],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "生地をこねて伸ばすところから作ると、いつものパスタが特別な一皿になる。",
    first_step: "強力粉と卵を用意し、生パスタのレシピを1つ選ぶ。",
    link: null,
  },
  {
    name: "日本茶や抹茶を点てる体験をする",
    category: "food",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [45, 90],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "静かに茶を点てる所作に集中するだけで、気持ちが落ち着いてくる。",
    first_step: "抹茶と茶筅を用意するか、体験できる教室を探す。",
    link: null,
  },
  {
    name: "クラフトビールの飲み比べをする",
    category: "food",
    indoor: true,
    with: ["partner", "friends"],
    energy: "low",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "銘柄ごとの違いを話しながら飲むと、会話も一緒に弾む。",
    first_step: "気になる銘柄を数種類、酒屋か通販で見繕う。",
    link: null,
  },
  {
    name: "郷土料理を再現して作ってみる",
    category: "food",
    indoor: true,
    with: ["solo", "partner", "family"],
    energy: "medium",
    minutes: [90, 150],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "知らない土地の味を再現してみると、行ったことのない場所に少し近づける。",
    first_step: "作ってみたい郷土料理を1つ決めてレシピを調べる。",
    link: null,
  },
  {
    name: "手作り味噌や梅干しなど発酵食品作りに挑戦する",
    category: "food",
    indoor: true,
    with: ["solo", "family"],
    energy: "medium",
    minutes: [90, 150],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["spring", "summer"],
    needs_prep: true,
    pitch: "時間をかけて発酵していく過程を見守るのも、この趣味ならではの楽しみ。",
    first_step: "手作りしたい発酵食品を1つ決めて材料キットを用意する。",
    link: null,
  },
  {
    name: "フルーツ狩りに出かける",
    category: "food",
    indoor: false,
    with: ["partner", "friends", "family"],
    energy: "medium",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: false,
    pitch: "その場で食べる採れたての果物は、お店で買うのとは別物の美味しさ。",
    first_step: "近隣でその季節に収穫体験ができる農園を調べる。",
    link: null,
  },
  {
    name: "高級ホテルのアフタヌーンティーを楽しむ",
    category: "food",
    indoor: true,
    with: ["partner", "friends"],
    energy: "low",
    minutes: [90, 150],
    budget: "unlimited",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "目にも楽しいスイーツを囲む時間は、それだけで贅沢な気分になれる。",
    first_step: "行ってみたいホテルのアフタヌーンティーを予約する。",
    link: null,
  },

  // ---- appreciation (11) ----
  {
    name: "オーケストラやクラシックコンサートを聴きに行く",
    category: "appreciation",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [120, 150],
    budget: "unlimited",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "生の音の重なりを浴びる体験は、音源で聴くのとはまったく違う。",
    first_step: "行きたい公演を1つ選び、座席とチケットの有無を確認する。",
    link: null,
  },
  {
    name: "歌舞伎や能など伝統芸能を観に行く",
    category: "appreciation",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [120, 180],
    budget: "unlimited",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "独特の様式美に触れると、知らなかった日本文化の奥深さに気づける。",
    first_step: "公演スケジュールを調べてチケットを確認する。",
    link: null,
  },
  {
    name: "野外彫刻や現代アート作品を見て回る",
    category: "appreciation",
    indoor: false,
    with: ["solo", "partner", "friends"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "屋外に置かれた作品を歩いて巡るだけで、ちょっとした散策気分になる。",
    first_step: "近隣で野外彫刻やアート作品が見られる公園を調べる。",
    link: null,
  },
  {
    name: "ミュージカルを観に行く",
    category: "appreciation",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "low",
    minutes: [120, 180],
    budget: "unlimited",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "歌と物語が一体になった舞台は、観終わったあとの余韻が長く続く。",
    first_step: "上演中のミュージカルを調べてチケットを確認する。",
    link: null,
  },
  {
    name: "動物園でのんびり動物を観察する",
    category: "appreciation",
    indoor: false,
    with: ["partner", "family", "friends"],
    energy: "low",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "動物をただ眺めているだけで、時間を忘れてリラックスできる。",
    first_step: "近くの動物園の営業時間を調べる。",
    link: null,
  },
  {
    name: "街の有名建築を外から眺めて歩く",
    category: "appreciation",
    indoor: false,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "建物のデザインに目を向けて歩くだけで、見慣れた街が違って見える。",
    first_step: "気になる建築をいくつか調べて、歩けるルートを決める。",
    link: null,
  },
  {
    name: "オーディオブックや朗読劇をじっくり聴く",
    category: "appreciation",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "目を閉じて言葉だけに集中すると、想像力がいつも以上に働く。",
    first_step: "気になる作品のオーディオブックか朗読劇を1つ選ぶ。",
    link: null,
  },
  {
    name: "サーカスや大道芸のパフォーマンスを観る",
    category: "appreciation",
    indoor: true,
    with: ["partner", "friends", "family"],
    energy: "low",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "目の前で繰り広げられる技の数々に、思わず声が出るほど引き込まれる。",
    first_step: "今月開催されるサーカスや大道芸イベントがないか探す。",
    link: null,
  },
  {
    name: "天体望遠鏡を使った観望会に参加する",
    category: "appreciation",
    indoor: false,
    with: ["partner", "family"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny"],
    seasons: ["autumn", "winter"],
    needs_prep: false,
    pitch: "望遠鏡越しに見る星は、肉眼で見るのとは迫力がまったく違う。",
    first_step: "近隣の天文台や公民館が開く観望会を調べる。",
    link: null,
  },
  {
    name: "ミニシアターで短編・単館系の映画を観る",
    category: "appreciation",
    indoor: true,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [90, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "普段選ばない作品に出会えるのが、こういう場所ならではの楽しみ。",
    first_step: "近くのミニシアターの上映スケジュールを調べる。",
    link: null,
  },
  {
    name: "骨董市や古美術展を見に行く",
    category: "appreciation",
    indoor: false,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "一つひとつの品に流れてきた時間を想像するだけで、面白い時間になる。",
    first_step: "週末に立つ骨董市や古美術展を1つ見つけて出かける。",
    link: null,
  },

  // ---- rest (11) ----
  {
    name: "温泉やスーパー銭湯でゆっくり湯につかる",
    category: "rest",
    indoor: true,
    with: ["solo", "partner", "family"],
    energy: "low",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "大きな湯船に浸かるだけで、自宅の風呂とは違う解放感がある。",
    first_step: "近くの温泉やスーパー銭湯の営業時間を調べる。",
    link: null,
  },
  {
    name: "耳かきやイヤーエステでリラックスする",
    category: "rest",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [45, 60],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "人にケアしてもらう時間は、それだけで肩の力がふっと抜ける。",
    first_step: "近くの耳かき専門店やイヤーエステの予約状況を確認する。",
    link: null,
  },
  {
    name: "睡眠瞑想(ヨガニドラ)で深く体を休める",
    category: "rest",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [20, 40],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "横になったまま声に導かれるだけで、寝たとき以上に体がゆるむ。",
    first_step: "ヨガニドラの音声ガイドを1つ選んで横になる。",
    link: null,
  },
  {
    name: "デジタルデトックスで1日スマホを触らないと決める",
    category: "rest",
    indoor: true,
    with: ["solo", "partner", "family"],
    energy: "low",
    minutes: [240, 480],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "通知から離れるだけで、頭の中の余白がはっきり増える。",
    first_step: "家族や友人にスマホを見ない時間を伝えておく。",
    link: null,
  },
  {
    name: "星空や雲をただ眺めてぼーっとする",
    category: "rest",
    indoor: false,
    with: ["solo", "partner"],
    energy: "low",
    minutes: [20, 40],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "空を見上げているだけの時間は、何も生み出さなくても十分価値がある。",
    first_step: "ベランダや庭など、空が見える場所に椅子を持っていく。",
    link: null,
  },
  {
    name: "ペットと一緒にソファでゴロゴロ過ごす",
    category: "rest",
    indoor: true,
    with: ["solo", "partner", "family"],
    energy: "low",
    minutes: [60, 180],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "一緒にいるだけでいい存在がそばにいる時間は、それだけで癒やされる。",
    first_step: "予定を空けて、ペットと過ごす時間を確保する。",
    link: null,
  },
  {
    name: "お香を焚いて静かに過ごす",
    category: "rest",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [30, 60],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "香りが部屋に満ちていく時間は、それだけで気持ちが落ち着いていく。",
    first_step: "好きな香りのお香とお香立てを用意する。",
    link: null,
  },
  {
    name: "整体やマッサージ店でプロにほぐしてもらう",
    category: "rest",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [60, 90],
    budget: "unlimited",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "自分では届かない凝りをほぐしてもらうと、体が一回り軽くなる。",
    first_step: "近くの整体やマッサージ店の予約状況を確認する。",
    link: null,
  },
  {
    name: "温かい飲み物を片手に窓の外をぼんやり眺める",
    category: "rest",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [15, 30],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "特別なことをしなくても、湯気を眺めているだけで心が落ち着く。",
    first_step: "好きな飲み物を淹れて、窓の見える場所に座る。",
    link: null,
  },
  {
    name: "目的地を決めずにふらっと散歩する",
    category: "rest",
    indoor: false,
    with: ["solo"],
    energy: "low",
    minutes: [30, 60],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "どこへ行くか決めないまま歩くと、いつもと違う道に気づける。",
    first_step: "家を出て、気になった方向にとりあえず歩いてみる。",
    link: null,
  },
  {
    name: "好きな音楽をただ聴くためだけの時間を作る",
    category: "rest",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [30, 60],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "何かをしながらではなく、聴くことだけに集中すると新しい発見がある。",
    first_step: "好きなアルバムを1枚選び、他のことをせず聴く時間を確保する。",
    link: null,
  },

  // ---- social (11) ----
  {
    name: "手紙や葉書を書いて誰かに送る",
    category: "social",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [20, 40],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "手を動かして言葉を選ぶ時間は、メッセージアプリとは違う気持ちが込められる。",
    first_step: "便箋とペンを用意し、送りたい相手を1人思い浮かべる。",
    link: null,
  },
  {
    name: "遠くに住む友人に電話をかけてゆっくり話す",
    category: "social",
    indoor: true,
    with: ["solo"],
    energy: "low",
    minutes: [30, 60],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "声を聞くだけで、しばらく会えていなかった距離がぐっと縮まる。",
    first_step: "話したい友人を1人思い浮かべて電話をかける。",
    link: null,
  },
  {
    name: "地域のお祭りやイベントに参加する",
    category: "social",
    indoor: false,
    with: ["partner", "friends", "family"],
    energy: "medium",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["summer", "autumn"],
    needs_prep: false,
    pitch: "地元の熱気に混ざるだけで、いつもの街が少し特別に感じられる。",
    first_step: "近隣で開催されるお祭りやイベントの日程を調べる。",
    link: null,
  },
  {
    name: "パートナーとこれからのことをゆっくり話す時間を作る",
    category: "social",
    indoor: true,
    with: ["partner"],
    energy: "low",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "予定を空けて向き合うだけで、普段話せないことも話しやすくなる。",
    first_step: "落ち着いて話せる時間と場所を決めて、パートナーを誘う。",
    link: null,
  },
  {
    name: "友人とスポーツ観戦を一緒に楽しむ",
    category: "social",
    indoor: true,
    with: ["friends"],
    energy: "medium",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "一緒に一喜一憂できる相手がいると、観戦の楽しさが何倍にもなる。",
    first_step: "観たい試合の日程を確認し、友人を誘う。",
    link: null,
  },
  {
    name: "ご近所さんと立ち話をしてみる",
    category: "social",
    indoor: false,
    with: ["solo"],
    energy: "low",
    minutes: [10, 20],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "ちょっとした会話でも、顔見知りが増えると暮らしが少し心強くなる。",
    first_step: "庭先や共用スペースで会ったときに、一言挨拶から始めてみる。",
    link: null,
  },
  {
    name: "同窓会や交流会を自分で企画してみる",
    category: "social",
    indoor: true,
    with: ["friends"],
    energy: "medium",
    minutes: [120, 240],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "声をかける側に回ってみると、思っていたより多くの人が集まってくれる。",
    first_step: "会いたいメンバーをリストアップして、候補日を連絡する。",
    link: null,
  },
  {
    name: "友人と一緒に新しいカフェを開拓する",
    category: "social",
    indoor: false,
    with: ["friends"],
    energy: "low",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "一緒に「当たり」を探す過程も含めて、友人との時間が楽しくなる。",
    first_step: "行ったことのないカフェを友人と2〜3軒リストアップする。",
    link: null,
  },
  {
    name: "家族や友人と写真を撮りに出かける(フォトウォーク)",
    category: "social",
    indoor: false,
    with: ["partner", "friends", "family"],
    energy: "medium",
    minutes: [90, 180],
    budget: "free",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "カメラを持って歩くだけで、いつもの景色が撮りたい被写体に変わる。",
    first_step: "カメラかスマホを持って、歩きたいエリアを決める。",
    link: null,
  },
  {
    name: "同じ趣味を持つ人たちのオフ会やイベントに参加する",
    category: "social",
    indoor: true,
    with: ["friends"],
    energy: "medium",
    minutes: [90, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "好きなものを気兼ねなく語れる相手に出会えると、趣味がさらに楽しくなる。",
    first_step: "参加しているコミュニティのオフ会情報を調べて申し込む。",
    link: null,
  },
  {
    name: "友人の家に遊びに行って手料理をごちそうになる",
    category: "social",
    indoor: true,
    with: ["friends"],
    energy: "low",
    minutes: [120, 240],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "誰かの手料理を囲むだけで、特別な準備がなくても十分なもてなしになる。",
    first_step: "仲のいい友人に連絡して、遊びに行く日程を決める。",
    link: null,
  },

  // ---- play (11) ----
  {
    name: "VRゲーム体験施設で非日常を味わう",
    category: "play",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "high",
    minutes: [60, 90],
    budget: "unlimited",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "現実にはない世界に没入できる体験は、何度やっても新鮮な驚きがある。",
    first_step: "近くのVR体験施設を調べて予約する。",
    link: null,
  },
  {
    name: "フォレストアドベンチャー(アスレチック)で体を動かして遊ぶ",
    category: "play",
    indoor: false,
    with: ["partner", "friends", "family"],
    energy: "high",
    minutes: [120, 180],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["spring", "summer", "autumn"],
    needs_prep: true,
    pitch: "木々の間を渡っていくスリルは、大人になっても十分楽しめる。",
    first_step: "近隣のフォレストアドベンチャー施設を調べて予約する。",
    link: null,
  },
  {
    name: "けん玉やコマなど昔ながらの遊びに挑戦する",
    category: "play",
    indoor: true,
    with: ["solo", "family"],
    energy: "low",
    minutes: [30, 60],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "シンプルな遊びほど、できるようになったときの嬉しさが大きい。",
    first_step: "家にあるけん玉やコマを探すか、手頃なものを1つ買う。",
    link: null,
  },
  {
    name: "縁日風の射的や輪投げを楽しむ",
    category: "play",
    indoor: true,
    with: ["partner", "friends", "family"],
    energy: "medium",
    minutes: [30, 60],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "単純なルールだからこそ、大人も子どもも一緒に本気になれる。",
    first_step: "射的や輪投げができるアミューズメント施設を探す。",
    link: null,
  },
  {
    name: "ジグソーパズルを1つ完成させる",
    category: "play",
    indoor: true,
    with: ["solo", "partner", "family"],
    energy: "low",
    minutes: [60, 240],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "ピースがはまっていく手応えは、地味だけど確実な達成感になる。",
    first_step: "好きな絵柄のジグソーパズルを1つ選んで用意する。",
    link: null,
  },
  {
    name: "麻雀を打つ",
    category: "play",
    indoor: true,
    with: ["friends"],
    energy: "medium",
    minutes: [120, 240],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "手牌を組み立てていく駆け引きは、何度やっても飽きない奥深さがある。",
    first_step: "雀荘を予約するか、友人にメンバーを声かけする。",
    link: null,
  },
  {
    name: "ダーツバーでダーツを楽しむ",
    category: "play",
    indoor: true,
    with: ["solo", "partner", "friends"],
    energy: "medium",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "的を狙って集中する時間は、仕事の考え事を忘れさせてくれる。",
    first_step: "近くのダーツバーの営業時間を確認する。",
    link: null,
  },
  {
    name: "パーティーゲームアプリで大人数で盛り上がる",
    category: "play",
    indoor: true,
    with: ["friends", "family"],
    energy: "medium",
    minutes: [60, 120],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "スマホ1台あれば準備いらずで盛り上がれる、集まりの強い味方。",
    first_step: "人数に合ったパーティーゲームアプリを1つインストールする。",
    link: null,
  },
  {
    name: "釣り堀で気軽に釣りを楽しむ",
    category: "play",
    indoor: false,
    with: ["solo", "partner", "family"],
    energy: "low",
    minutes: [60, 120],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "道具の準備がいらない分、思い立ったその日にすぐ楽しめる。",
    first_step: "近くの釣り堀の料金と営業時間を調べる。",
    link: null,
  },
  {
    name: "トレーディングカードゲームの対戦会に参加する",
    category: "play",
    indoor: true,
    with: ["friends"],
    energy: "medium",
    minutes: [90, 180],
    budget: "free",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: true,
    pitch: "知らない相手との対戦は、いつもと違う緊張感と発見がある。",
    first_step: "参加できるカードゲームショップの対戦会を調べる。",
    link: null,
  },
  {
    name: "エアホッケーやビリヤードで遊ぶ",
    category: "play",
    indoor: true,
    with: ["partner", "friends"],
    energy: "high",
    minutes: [45, 90],
    budget: "under3000",
    weather_ok: ["sunny", "cloudy", "rainy"],
    seasons: ["all"],
    needs_prep: false,
    pitch: "単純な駆け引きの勝負は、話が弾むきっかけにもなる。",
    first_step: "近くのゲームセンターやバーでプレイできる場所を探す。",
    link: null,
  },
];

const catalog = items.map((item, index) => ({
  id: `act_${String(index + 1).padStart(3, "0")}`,
  ...item,
}));

const parsed = ActivityCatalogSchema.parse(catalog);

writeFileSync(
  "data/activities.json",
  JSON.stringify(parsed, null, 2) + "\n",
  "utf-8"
);

console.log(`${parsed.length} 件を data/activities.json に書き出しました。`);
